name: plex-watchlist-sync

services:
  plex-watchlist-sync:
    build:
      context: ${WATCHLIST_SYNC_BUILD_CONTEXT:-..}
      dockerfile: docker/Dockerfile
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SYNC_INTERVAL_SECONDS: ${SYNC_INTERVAL_SECONDS:-30}
    volumes:
      - state:/config
    restart: unless-stopped
    stop_grace_period: 1m

volumes:
  state:
